overlayctl: add install and uninstall subcommands.
Signed-off-by: Pavel Pisa <ppisa@pikron.com>

diff --git a/init-overlay/sbin/overlayctl b/init-overlay/sbin/overlayctl
--- a/init-overlay/sbin/overlayctl
+++ b/init-overlay/sbin/overlayctl
@@ -1,4 +1,52 @@
 #!/bin/sh
+#
+# Root filesystem overlay control and install stript
+#
+# Copyright (C) 2014 Pavel Pisa <ppisa@pikron.com>
+
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation; either version 3 of the License, or
+# (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
+
+modify_boot_cmdline()
+{
+    if [ ! -e /boot/cmdline.txt ] ; then
+        umount_boot=yes
+        mount /boot || exit 1
+    fi
+    if [ ! -e /boot/cmdline.txt ] ; then
+        echo "/boot/cmdline.txt missing"
+        exit 1
+    fi
+    if [ ! -w /boot ] ; then
+        remount_boot_ro=yes
+        mount -o remount,rw /boot || exit 1
+    fi
+    if ! grep -q '/sbin/init-overlay' /boot/cmdline.txt ; then
+        cp /boot/cmdline.txt /boot/cmdline.bak
+    fi
+    rm -f /boot/cmdline.new
+    sed -e 's/\( \|^\)\(ro\|rw\)\( \|$\)/ /g' \
+        -e 's/\( \|^\)\(init=[^ ]*\)\( \|$\)/ /g' \
+        -e 's/^ //' -e 's/ $//' /boot/cmdline.txt \
+        -e 's#^\(.*root=.*\)$#\1'"$1"'#'\
+        >/boot/cmdline.new
+    mv /boot/cmdline.new /boot/cmdline.txt
+    if [ -n "$umount_boot" ] ; then
+        umount /boot
+    elif [ -n "$remount_boot_ro" ] ; then
+        mount -o remount,ro /boot
+    fi
+}
 
 overlay_is_active()
 {
@@ -71,6 +119,14 @@ case "$1" in
 
     unlock)
         mount -o remount,rw "$overlay_base"
+        ;;
+
+    install)
+        modify_boot_cmdline " ro init=/sbin/init-overlay"
+        ;;
+
+    uninstall)
+        modify_boot_cmdline " ro"
         ;;
 
     *)
